language: python

python:
  - "3.5"
  - "3.6"
  - "3.7-dev"

install:
  - pip install .
  - pip install flake8 autopep8
  - pip install codecov nose
  - apt-get install rustc gcc python2.7 python3.4

script:
  - flake8 --ignore=E501, W605
  - autopep8 -r . --diff | tee check_autopep8
  - test ! -s check_autopep8
  - atcoder-tools gen arc050 --without-login
  - nosetests tests --exe -v --with-coverage --cover-package=atcodertools
  - codecov
notifications:
  email: false
